### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by 752101** [daniely93/nodejs-server-maintenance#1]
TypeError: Cannot convert undefined or null to object
2021-08-02 17:20:32at Function.keys (<anonymous>)
2021-08-02 17:20:32at /usr/src/app/node_modules/nodejs-server-maintenance/index.js:47:18
2021-08-02 17:20:32at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
2021-08-02 17:20:32at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)
2021-08-02 17:20:32at checkAuthentication (/usr/src/app/node_modules/nodejs-server-maintenance/index.js:42:24)
2021-08-02 17:20:32at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
2021-08-02 17:20:32at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)
2021-08-02 17:20:32at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:112:3)

JSON Payload provided : 
{
   "filePath":null,
   "useApi":false,
   "statusCode":503,
   "message":"Maintenance Mode Raza 112",
   "blockPost":false
}

**Comment by OctipusV** [comment]
I'm currently experiencing the exact same issue, had any luck fixing it?

**Comment by 752101** [comment]
> I'm currently experiencing the exact same issue, had any luck fixing it?

OH yes, my bad.. Silly mistake.

You need to place this Middleware after your json body parser Middleware. So that it can read request body, for me it was reading request body as null thus throwing error during Key fetchin. 

// Hint : Body-parser Middleware looks something like this in your express code. So place your maintenance Middleware after this

app.use(bodyparser.json())

**Comment by daniely-93** [comment]
> I'm currently experiencing the exact same issue, had any luck fixing it?

> > I'm currently experiencing the exact same issue, had any luck fixing it?
> 
> OH yes, my bad.. Silly mistake.
> 
> You need to place this Middleware after your json body parser Middleware. So that it can read request body, for me it was reading request body as null thus throwing error during Key fetchin.
> 
> // Hint : Body-parser Middleware looks something like this in your express code. So place your maintenance Middleware after this
> 
> app.use(bodyparser.json())

are you using the latest version? the previous version had a key of `forceMessage` which has been deprecated. 
as you can see in the notes: 

The priority of the variables is
`useApi` - if true the server will send a JSON
`filePath` - if filePath is provided, the server will send that file
`message` - if above are false or null, the message will be sent by default

so by default if you don't set `filePath`, it should return the message as string.

Edit:

I saw the issue, locally it worked.. anyway I've pushed a fix (ver 2.0.5) and tested, should be ok now.

**Comment by 752101** [comment]
> > I'm currently experiencing the exact same issue, had any luck fixing it?
> 
> > > I'm currently experiencing the exact same issue, had any luck fixing it?
> > 
> > 
> > OH yes, my bad.. Silly mistake.
> > You need to place this Middleware after your json body parser Middleware. So that it can read request body, for me it was reading request body as null thus throwing error during Key fetchin.
> > // Hint : Body-parser Middleware looks something like this in your express code. So place your maintenance Middleware after this
> > app.use(bodyparser.json())
> 
> are you using the latest version? the previous version had a key of `forceMessage` which has been deprecated.
> as you can see in the notes:
> 
> The priority of the variables is
> `useApi` - if true the server will send a JSON
> `filePath` - if filePath is provided, the server will send that file
> `message` - if above are false or null, the message will be sent by default
> 
> so by default if you don't set `filePath`, it should return the message as string.
> 
> Edit:
> 
> I saw the issue, locally it worked.. anyway I've pushed a fix (ver 2.0.5) and tested, should be ok now.

Yes, latest version only 😄 

Issue is just the placement of body parser middleware .

_Line#47 in Index.js, req.body is used without validating if thats null or not_
if (req.body && **Object.keys(req.body).length**) {

**Comment by daniely-93** [comment]
> > > I'm currently experiencing the exact same issue, had any luck fixing it?
> > 
> > 
> > > > I'm currently experiencing the exact same issue, had any luck fixing it?
> > > 
> > > 
> > > OH yes, my bad.. Silly mistake.
> > > You need to place this Middleware after your json body parser Middleware. So that it can read request body, for me it was reading request body as null thus throwing error during Key fetchin.
> > > // Hint : Body-parser Middleware looks something like this in your express code. So place your maintenance Middleware after this
> > > app.use(bodyparser.json())
> > 
> > 
> > are you using the latest version? the previous version had a key of `forceMessage` which has been deprecated.
> > as you can see in the notes:
> > The priority of the variables is
> > `useApi` - if true the server will send a JSON
> > `filePath` - if filePath is provided, the server will send that file
> > `message` - if above are false or null, the message will be sent by default
> > so by default if you don't set `filePath`, it should return the message as string.
> > Edit:
> > I saw the issue, locally it worked.. anyway I've pushed a fix (ver 2.0.5) and tested, should be ok now.
> 
> Yes, latest version only 😄
> 
> Issue is just the placement of body parser middleware .
> 
> _Line#47 in Index.js, req.body is used without validating if thats null or not_
> if (req.body && **Object.keys(req.body).length**) {

Is that a warning or an error? I am unable to see it running locally, can you give me more details of what env you use? do you have TypeScript?

**Comment by daniely-93** [comment]
> {
> "filePath":null,
> "useApi":false,
> "statusCode":503,
> "message":"Maintenance Mode Raza 112",
> "blockPost":false
> }

I've added a note in README, in case someone else will experience the same issue please read: it also here

> The maintenance should be defined before your app routes and after your body parser

A note for the OP, you can send only the customized parameters you would like to change, e.g.
{
"message":"Maintenance Mode Raza 112"
}

will change only message, the rest params will use the default values unless you want to change them so you can add.
but remember that only these 5 values are allowed to be changed.
