### ISSUE TITLE
Suggest to add unauthorized callback when the accessKey is not correct

### ISSUE THREAD

**Issue by raymondnexsoftech** [daniely93/nodejs-server-maintenance#3]
As I don't want someone know there is a maintenance endpoint in my server, I would like to suggest to add something like unauthorizedCallback to let user control the return of the api

Here is the suggestion:

1) Add unauthorizedCallback in variable
2) Add the init data in _resetData function like the following:
```
    unauthorizedCallback = function (req, res, next) {return res.sendStatus(401)},
```
3) Add to save option:
```
unauthorizedCallback = options.unauthorizedCallback || unauthorizedCallback;
```

And user can add parameter like this in the option:
```
  unauthorizedCallback: function (req, res, next) { next(createError(404)) },
```
To change the return status of the api

**Comment by daniely-93** [comment]
Sorry for the late response, I added a third parameter as a middleware which cannot be changed through the API.

If you want to handle the access to the `endpoint` by yourself, you can add a function.
It allows you to hide the endpoint API and control the response.

    const maintenance = require('nodejs-server-maintenance');
    
    // options
    
	const middleware = (req, res, next) => {
		try {
			// you can verify the token if you use jwt or have other conditions
			const  token  =  req.headers.authorization.split("  ")[1];
			if (token  ===  "token1234") return  next();
			throw  new  Error();
		} catch (error) {
			res.sendStatus(404);	
		}
	};
	
    maintenance(app, options, middleware);

You can update to the latest version 2.1.0.
